version: '3.7'

x-node-env: &node-env
  NODE_ENV: development
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-service: &node-service
  tty: true
  init: true
  image: node:16.13-alpine
  working_dir: /stocktrax
  volumes:
    - .:/stocktrax:cached
    - ./node_modules:/stocktrax/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *node-env

services:
  app:
    <<: *node-service
    working_dir: /stocktrax/app
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *node-env
      HOST: app-stocktrax.dev.parameter1.com
      PORT: 38670
      VITE_GRAPHQL_URL: ${VITE_GRAPHQL_URL-http://graphql-stocktrax.dev.parameter1.com:38671}
    depends_on:
      - graphql
    ports:
      - "38670:38670"
    hostname: app-stocktrax.dev.parameter1.com

  graphql:
    <<: *node-service
    working_dir: /stocktrax/graphql
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *node-env
      EXPOSED_HOST: graphql-stocktrax.dev.parameter1.com
      EXPOSED_PORT: 38671
      HOST: graphql-stocktrax.dev.parameter1.com
      IEX_CLOUD_PUBLISHABLE_API_TOKEN: ${IEX_CLOUD_PUBLISHABLE_API_TOKEN-}
      MONGO_URL: ${MONGO_URL-mongodb://root:password123@mongodb-primary:27017,mongodb-secondary:27017/?authSource=admin&readPreference=primary}
      SHUTDOWN_GRACE_PERIOD: 0
    hostname: graphql-stocktrax.dev.parameter1.com
    ports:
      - "38671:80"
    depends_on:
      - mongodb-secondary

  cli:
    <<: *node-service
    working_dir: /stocktrax/cli
    entrypoint: ["node"]
    command: ["src"]
    environment:
      <<: *node-env
      IEX_CLOUD_PUBLISHABLE_API_TOKEN: ${IEX_CLOUD_PUBLISHABLE_API_TOKEN-}
      MONGO_URL: ${MONGO_URL-mongodb://root:password123@mongodb-primary:27017,mongodb-secondary:27017/?authSource=admin&readPreference=primary}
    depends_on:
      - mongodb-secondary

  commands:
    <<: *node-service
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb-primary:
    image: bitnami/mongodb:5.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=stocktrax
    volumes:
      - mongodb-primary:/bitnami
    ports:
      - "39671:27017"

  mongodb-secondary:
    image: bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=stocktrax
    volumes:
      - mongodb-secondary:/bitnami

volumes:
  yarn-cache: {}
  mongodb-primary: {}
  mongodb-secondary: {}
